import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import HanatYomaImg from "../public/images/hanatyoma.jpg";
import KrabiImg from "../public/images/marcin-kalinski-PCgM2CYm6HA-unsplash-min.jpg";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={``}>
        <section
          className={`my-2 py-2 bg-cover bg-center `}
          styles={{
            backgroundImage: `url('public/images/marcin-kalinski-PCgM2CYm6HA-unsplash-min.jpg')`,
          }}
        >
          <div>
            <h1 className={`text-5xl text-center`}>Hanat Yoma</h1>
          </div>
          <div className={`mx-auto text-center my-2 py-1 border-4  border-x-sky-500 border-y-sky-600 rounded-full object-cover w-[724px] h-[724px]`}>
            <Image
              className={`object-cover h-auto object-bottom rounded-full`}
              src={HanatYomaImg}
              alt="Hanat Yoma Pic"
              height={`724`}
              width={`724`}
            />
          </div>
          <div className="rounded-full aspect-h-3 aspect-w-4 w-60">
            <Image src={KrabiImg} alt={`Krabi `} />
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
